### ISSUE TITLE
Failed to activate the draw-package package

### ISSUE THREAD

**Issue by eapearson** [erkkikeranen/draw-package#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [draw-package](https://github.com/erkkikeranen/draw-package) package, v0.1.1
### Stack Trace

Failed to activate the draw-package package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/erik/.atom/packages/draw-package/lib/draw-package.coffee:14:27)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```
### Commands

```
     -4:13.8.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -4:11.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:11.3.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -4:09.8.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -4:09.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:08.9.0 core:delete (atom-text-editor.editor.is-focused)
     -4:07.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:04.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:03.9.0 core:paste (atom-text-editor.editor.is-focused)
     -3:00.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -3:00.0 snippets:expand (atom-text-editor.editor.is-focused)
     -3:00.0 editor:indent (atom-text-editor.editor.is-focused)
  5x -2:48 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -2:46.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:12.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:11.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "native-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
bottom-dock, v0.3.5
draw-package, v0.1.1
language-rust, v0.4.5
markdown-preview-plus, v2.2.2
markdown-writer, v2.0.1
native-ui, v0.8.0
pandoc-convert, v1.0.4
quantum-shell, v0.7.0
terminal-plus, v0.14.0

# Dev
No dev packages
```

**Comment by Ehekatl** [comment]
+1

**Comment by codeshrew** [comment]
+1

**Comment by erkkikeranen** [comment]
I've fixed the deprecation please download the new version.
